---
title: "R Workshops/Seminars that I was involved with"
author: "Anna Quaglieri"
date: "01/03/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 2019

## R-Ladies Melbourne Meetup: [Producing publication-ready documents in R Markdown](Producing publication-ready documents in R Markdown) 

Find [material and references](http://rpubs.com/annaquagli/471405) that I presented about writing journal articles with `bookdown` and other alternatives.  

## Blog post about [Everyday life tips as the R-Ladies Melbourne team](https://r-ladiesmelbourne-team.netlify.com/)

## Blog post about [R-Ladies Melbourne 2017-2018 highlights!](https://rladiesmelb2018.netlify.com/)


# 2018

## Invited talk at Bioconductor Asia conference: [R-Ladies: An update on the local and wider picture](https://github.com/annaquaglieri16/BiocAsia---R-Ladies-An-update-on-the-local-and-wider-picture)

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Next up <a href="https://twitter.com/annaquagli?ref_src=twsrc%5Etfw">@annaquagli</a> describing the amazing growth with <a href="https://twitter.com/RLadiesMelb?ref_src=twsrc%5Etfw">@RLadiesMelb</a>! <a href="https://twitter.com/hashtag/rladies?src=hash&amp;ref_src=twsrc%5Etfw">#rladies</a> <a href="https://twitter.com/hashtag/biocAsia?src=hash&amp;ref_src=twsrc%5Etfw">#biocAsia</a> <a href="https://t.co/YPsNTi6mUf">pic.twitter.com/YPsNTi6mUf</a></p>&mdash; Stephanie Hicks (@stephaniehicks) <a href="https://twitter.com/stephaniehicks/status/1068295570509316096?ref_src=twsrc%5Etfw">November 30, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Tutorial at useR! R: [Looking to clean your data? Learn how to Remove Unwanted Variation with R - Part 2](https://www.youtube.com/watch?v=HUcZQC3xWDo&list=PL4IzsxWztPdnyAKQQLxA4ucpaCLdsKvZw&index=4) 

Find [material used](https://github.com/annaquaglieri16/ruv-useR2018).  


## Tutorial at useR! R: [Follow Me: Introduction to social media analysis in R - Part 2](https://www.youtube.com/watch?v=DvQEHhP6pVo&list=PL4IzsxWztPdnyAKQQLxA4ucpaCLdsKvZw&index=18) 

Find [material used](https://github.com/annaquaglieri16/Follow-Me-Introduction-to-social-media-analysis-in-R).


# 2017 


## R-Ladies Melbourne Meetup [Twitter in R workshop](https://www.meetup.com/R-Ladies-Melbourne/events/239791772/)

Find [material and references](https://github.com/annaquaglieri16/Melbourne-Twitter-workshop) that I presented. 


## [COMBINE Bioconductor Melbourne workshop](https://combine-australia.github.io/2017-05-19-bioconductor-melbourne/)





